export const COUPON_ENDPOINT="http://localhost:3000/coupon"
export const CART_ENDPOINTS="http://localhost:3000/cart"
export const PRODUCT_ENDPOINTS="http://localhost:3000/product"
export const USER_ENDPOINTS="http://localhost:3000/user"
export const OFFER_ENDPOINTS="http://localhost:3000/offer"