// export const COUPON_ENDPOINT="http://localhost:3000/coupon"
// export const CART_ENDPOINTS="http://localhost:3000/cart"
// export const PRODUCT_ENDPOINTS="http://localhost:3000/product"
// export const USER_ENDPOINTS="http://localhost:3000/user"
// export const OFFER_ENDPOINTS="http://localhost:3000/offer"
// export const BASE_URL="http://localhost:3000"

export const COUPON_ENDPOINT="https://malikpetshop.onrender.com/coupon"
export const CART_ENDPOINTS="https://malikpetshop.onrender.com/cart"
export const PRODUCT_ENDPOINTS="https://malikpetshop.onrender.com/product"
export const USER_ENDPOINTS="https://malikpetshop.onrender.com/user"
export const OFFER_ENDPOINTS="https://malikpetshop.onrender.com/offer"
export const BASE_URL="https://malikpetshop.onrender.com"